### ISSUE TITLE
Database failure while installing the package

### ISSUE THREAD

**Issue by bharathapj17** [msopentechcn/odata-plugin-for-sugarcrm#2]
Hi All,

I am trying to install Odata Plugin for SugarCRM version 6.5.26. Bur when I upload this plugin and try to install, I am getting Database failure error as below in the sugarcrm.log file

> 11/20/17 10:55:59 [1160][1][FATAL] Error creating table: suga_sugarodata: Query Failed: CREATE TABLE suga_sugarodata (id char(36)  NOT NULL ,name varchar(255)  NULL ,date_entered datetime  NULL ,date_modified datetime  NULL ,modified_user_id char(36)  NULL ,created_by char(36)  NULL ,description text  NULL ,deleted bool  DEFAULT '0' NULL ,assigned_user_id char(36)  NULL ,tablename varchar(255)  NULL  , PRIMARY KEY (id),   KEY idx_suga_sugarodata_tmst_id (team_set_id)) CHARACTER SET utf8 COLLATE utf8_general_ci
> 
> MySQL error 1072: Key column 'team_set_id' doesn't exist in table

Please help me resolve this issue. 

I am using Windows server 2012 R2 OS. 
PHP Version 5.6.31
Apache 2.0 API Handler

Regards,
Bharath

**Comment by v-wjia** [comment]
sorry for my delayed reply. please see this
If your server is Linux, after installation, you have to add /yourpathtosugarcrm/odata/library this path to your php.ini include_path, in order to add this library code through PHP ‘Include_path’.
Did you add this path to your include_path?

**Comment by ecalderon123** [comment]
This Zip works with Sugar (version 9.2.0) ?  
I should download all the files in one Zip file?

Kind REgards!

**Comment by ecalderon123** [comment]
This Zip works with Sugar (version 9.2.0) ?
I should download all the files in one Zip file?

Kind REgards!

**Comment by andresvettori** [comment]
I'm having this exact same issue on SugarCRM CE 6.5.26 on UBUNTU, but I don't know what path to add in php.ini to include_path. 

My php.ini is located in /etc/php5/apache2/php.ini 
My SugarCRM is installed on /var/www/html/sugar

So, exactly what path I need to add?

Thanks in advance.
Agv

**Comment by v-wjia** [comment]
> I'm having this exact same issue on SugarCRM CE 6.5.26 on UBUNTU, but I don't know what path to add in php.ini to include_path.
> 
> My php.ini is located in /etc/php5/apache2/php.ini
> My SugarCRM is installed on /var/www/html/sugar
> 
> So, exactly what path I need to add?
> 
> Thanks in advance.
> Agv

I think it will be /var/www/html/sugar/odata/library to you.
